name: maskedrealm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  google_mobile_ads: ^6.0.0
  http: ^1.3.0
  provider: ^6.1.4
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.1.7
  webview_flutter: ^4.11.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/background.jpg
